/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matrizdlistaligadaforma2;

import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Personal
 */
public class Ejecutable extends javax.swing.JFrame {
    private String clave = "admin";
    private String usuarios = "admin";
    private int[][] matCostos;
    private String[] estaciones;//contiene los nombres de las estaciones
    public int[][] matTemp;
    public String[] estTemp;
    public JFrame lienzo;
    public JPanel pin;
    public boolean banderita = true;
    JTextArea areamatriz = new JTextArea();
    MatrizListaligadaforma2 obj;
    private int filas;
    private int columnas;

    /**
     * Creates new form Ejecutable
     */
    public Ejecutable() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getIconImage();
    }
    
    public String getClave() {
        return clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

    public String getUsuarios() {
        return usuarios;
    }

    public void setUsuarios(String usuarios) {
        this.usuarios = usuarios;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BcerrarS = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        textuser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textpass = new javax.swing.JPasswordField();
        errorPass = new javax.swing.JLabel();
        BInicio = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Bcarga = new javax.swing.JButton();
        Bedit = new javax.swing.JButton();
        BcerrarS1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textConfirmacion = new javax.swing.JTextArea();
        Bok = new javax.swing.JButton();
        Bcancelar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        BcerrarS.setBackground(new java.awt.Color(255, 255, 255));
        BcerrarS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BcerrarS.setText("Cerrar Sesión");
        BcerrarS.setEnabled(false);
        BcerrarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcerrarSActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(723, 490));

        jButton1.setText("Ver Matriz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ver Grafo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(455, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(384, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Matriz Led", jPanel1);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Usuario: ");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Clave:");

        textpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpassActionPerformed(evt);
            }
        });

        errorPass.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        BInicio.setBackground(new java.awt.Color(255, 255, 255));
        BInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BInicio.setText("Iniciar");
        BInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInicioActionPerformed(evt);
            }
        });

        Bcarga.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bcarga.setText("Cargar Archivo");
        Bcarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BcargaMouseClicked(evt);
            }
        });
        Bcarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcargaActionPerformed(evt);
            }
        });

        Bedit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bedit.setText("Editar Credenciales");
        Bedit.setEnabled(false);
        Bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeditActionPerformed(evt);
            }
        });

        BcerrarS1.setBackground(new java.awt.Color(255, 255, 255));
        BcerrarS1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BcerrarS1.setText("Cerrar Sesión");
        BcerrarS1.setEnabled(false);
        BcerrarS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcerrarS1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Confirmación:");

        textConfirmacion.setColumns(20);
        textConfirmacion.setRows(5);
        textConfirmacion.setEnabled(false);
        jScrollPane3.setViewportView(textConfirmacion);

        Bok.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bok.setText("Ok");
        Bok.setEnabled(false);
        Bok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BokActionPerformed(evt);
            }
        });

        Bcancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bcancelar.setText("Cancelar");
        Bcancelar.setEnabled(false);
        Bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jLabel9)))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textuser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textpass, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(errorPass, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(BcerrarS1))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(BInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bedit, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Bok)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Bcancelar))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(Bcarga, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(textuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(textpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(errorPass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BcerrarS1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Bcarga, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bedit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bcancelar)
                            .addComponent(Bok))
                        .addGap(27, 27, 27))))
            .addComponent(jSeparator2)
        );

        jTabbedPane1.addTab("Administrador", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MatrizCargar(String entrada){
        String filass,columnass;
        int cFilas,cColumnas;
        String[] lineas = entrada.split("\n");
        filass = lineas[0].trim();
        columnass = lineas[1].trim();
        filas=Integer.parseInt(filass);
        columnas=Integer.parseInt(columnass);
        obj = new MatrizListaligadaforma2(filas,columnas);
        for (int i = 2; i <lineas.length; i++) {
            String []colaboradorT,temp,temporal;
            
            temp=lineas[i].split("-");
            colaboradorT=new String[temp.length+1];
            temporal=temp[1].split("=");
            
            for (int j = 0; j <temp.length; j++) {
                colaboradorT[j]=temp[j].trim();
                
            }
            
            colaboradorT[1]=temporal[0];
            colaboradorT[2]=temporal[1];
            int []colaborador=new int[colaboradorT.length];
            char problematico=colaboradorT[2].charAt(0);
            colaborador[0]=Integer.parseInt(colaboradorT[0]);
            colaborador[1]=Integer.parseInt(colaboradorT[1]);
            colaborador[2]=Integer.parseInt(Character.toString(problematico)); 
            CrearMatriz(colaborador[0], colaborador[1],colaborador[2]);
            //obj.setCelda(colaborador[0], colaborador[1],colaborador[2]);
        }
    }
    
    private void CrearMatriz(int filaInicial,int filaFinal,int valor){
        int z=filas-1;
        int w,x,y=0;
        for (int i = filaInicial; i <= filaFinal; i++) {
            w=i;
            if (i>filas) {
                w=i%filas;
                if (w==0) {
                    w=filas;
                }
            }
            x=filas-w;
            if (z!=0) {
                y=columnas-1;
                z--;
            }else{
                z=filas-1;
                y=columnas-1;
                columnas--;
            }
            
            obj.setCelda(x,y,valor);
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpassActionPerformed

    private void BInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInicioActionPerformed
        String messErr;
        try {
            String user = textuser.getText();
            char[] pass = textpass.getPassword();

            if (user.equals(usuarios)) {
                if (clave.equals(String.valueOf(pass))) {
                    Bcarga.setEnabled(true);
                    Bedit.setEnabled(true);
                    BcerrarS.setEnabled(true);
                } else {
                    messErr = "Contraseña Incorrecta";
                    errorPass.setText(messErr);
                }

            } else {
                messErr = "Usuario Incorrecto";
                errorPass.setText(messErr);
            }

        } catch (Exception e) {
        }
        textuser.setText("");
        textpass.setText("");
    }//GEN-LAST:event_BInicioActionPerformed

    private void BcargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcargaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BcargaMouseClicked

    private void BcargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcargaActionPerformed
        JFileChooser buscar = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("TXT", "txt");
        buscar.setFileFilter(filtro);
        String cadena = "";
        int selecion = buscar.showOpenDialog(this);

        if (selecion == JFileChooser.APPROVE_OPTION) {
            File archivo = buscar.getSelectedFile();
            try (FileReader fr = new FileReader(archivo)) {

                int linea = fr.read();
                while (linea != -1) {
                    cadena += (char) linea;
                    linea = fr.read();
                }
                //this.textConfirmacion.setText(cadena);
            } catch (Exception e) {
            }
        }
        //CrearMatCostosyVecEstaciones(cadena);
        MatrizCargar(cadena);
        //Bedit.setEnabled(false);
        Bcarga.setEnabled(false);
        Bok.setEnabled(true);
        Bcancelar.setEnabled(true);
        textConfirmacion.setText(cadena);
    }//GEN-LAST:event_BcargaActionPerformed

    private void BeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeditActionPerformed
        setUsuarios(JOptionPane.showInputDialog(null, "Ingrese el nuevo usuario"));
        setClave(JOptionPane.showInputDialog(null, "Ingrese la nueva clave"));
        //Bedit.setEnabled(false);
        //Bcarga.setEnabled(false);
    }//GEN-LAST:event_BeditActionPerformed

    private void BcerrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcerrarSActionPerformed
        Bcarga.setEnabled(false);
        Bedit.setEnabled(false);
        BcerrarS.setEnabled(false);
    }//GEN-LAST:event_BcerrarSActionPerformed

    private void BcerrarS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcerrarS1ActionPerformed
        Bcarga.setEnabled(false);
        Bedit.setEnabled(false);
        BcerrarS.setEnabled(false);
    }//GEN-LAST:event_BcerrarS1ActionPerformed

    private void BokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BokActionPerformed
        /*if (matTemp != null && estTemp != null) {
            setMatCostos(matTemp);
            setEstaciones(estTemp);
            JOptionPane.showMessageDialog(null, "Las estaciones Se han cargado satisfactoreamente");
            textConfirmacion.setText("");
            Bok.setEnabled(false);
            Bcancelar.setEnabled(false);
            Bcarga.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Algo Salio Mal\n \t"
                + "favor revisar el Archivo y proceda a cargarlo nuevamente.\n \t"
                + "Gracias.");
        }*/
    }//GEN-LAST:event_BokActionPerformed

    private void BcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcancelarActionPerformed
        JOptionPane.showMessageDialog(null, "No se guardaron cambios ");
        textConfirmacion.setText("");
    }//GEN-LAST:event_BcancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println(obj);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejecutable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejecutable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejecutable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejecutable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejecutable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BInicio;
    private javax.swing.JButton Bcancelar;
    private javax.swing.JButton Bcarga;
    private javax.swing.JButton BcerrarS;
    private javax.swing.JButton BcerrarS1;
    private javax.swing.JButton Bedit;
    private javax.swing.JButton Bok;
    private javax.swing.JLabel errorPass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea textConfirmacion;
    private javax.swing.JPasswordField textpass;
    private javax.swing.JTextField textuser;
    // End of variables declaration//GEN-END:variables
}
